### ISSUE TITLE
Apache legal claims

### ISSUE THREAD

**Issue by escitalopram** [gentics/changelog-manager-plugin#3]
The Apache foundation claims any naming pattern `maven-xyz-plugin` for its »Apache Maven«-trademark:
https://maven.apache.org/guides/plugin/guide-java-plugin-development.html

They even have their own  `maven-changelog-plugin` going:
http://maven.apache.org/plugins/maven-changelog-plugin/project-summary.html

To be on the safe side, I'd suggest renaming the repository and changing occurrences of »Maven Changelog Plugin« in the docs according to the actual artifact name of `changelog-manager-plugin`.

**Comment by Jotschi** [comment]
Project renamed

**Comment by Jotschi** [comment]
No other source code references to the old name could be found. Thank you for the issue.
